### ISSUE TITLE
Wrong Docs regarding Package.swift

### ISSUE THREAD

**Issue by stherold** [mono0926/LicensePlist#140]
When using SPM from Xcode there is no Package.swift as suggested in:
```
If you are using Swift Package Manager inside Xcode, you can use --package-path $PROJECT_FILE_PATH/project.xcworkspace/xcshareddata/swiftpm/Package.swift inside your Run script.
```

What exactly is meant by this? It should be removed imho. When using SPM from Xcode the resolved package info is stored in 
`$PROJECT_FILE_PATH/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` and the package info itself in `project.pbxproj`

**Comment by buechner** [comment]
For me it looks like the packages are automatically read from the xcode project file. This is awesome and unexpected for me. This should be documented.

**Comment by stherold** [comment]
Ahhhh I understand. This is possible...

**Comment by markusfassbender-parshipgroup** [comment]
I had an issue with that one too. The app uses a custom Swift Package `Utilities` that itself has dependencies for example to `swift-log`. So the tool didn't find those ones itself.

✅ I solved this by using:
`--package-path $SRCROOT/<projectname>.xcworkspace/xcshareddata/swiftpm/Package.resolved`

⚠️  @stherold your suggestion of `$PROJECT_FILE_PATH/project.xcworkspace/` didn't work for me, because this was looking into the `project.xcodeproj/project.xcworkspace`, that is not the right one. The right xcworkspace is on the same level as the xcodeproj!

**Comment by yosshi4486** [comment]
Same issue here.

**Comment by mono0926** [comment]
@stherold @markusfassbender-parshipgroup 

The pull request(created by @yosshi4486 🙏) , was merged, and [3.0.7](https://github.com/mono0926/LicensePlist/releases/tag/3.0.7) was released.
Is the problem fixed now?

**Comment by yosshi4486** [comment]
@stherold @markusfassbender-parshipgroup 
Hi. I found that the implementation eventually use Package.resolved even if you specify Package.swift.

https://github.com/mono0926/LicensePlist/blob/fa4699f642bf4f835009ef6e957cbe2728db540d/Sources/LicensePlistCore/Entity/FileReader/SwiftPackageFileReader.swift#L26-L34

**Comment by yosshi4486** [comment]
and I've updated README.md.

<img width="1035" alt="スクリーンショット 2021-04-09 14 45 59" src="https://user-images.githubusercontent.com/9734876/114134248-5fdad400-9942-11eb-9606-8b9c9faa8544.png">

**Comment by markusfassbender-parshipgroup** [comment]
Yes thank you, this fixes it and also the documentation is much clearer now. Thank you! 💯
